name: nightly-docs

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 6 * * *'

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: ./geomesa.github.io
      - name: Checkout GeoMesa source
        uses: actions/checkout@v2
        with:
          repository: locationtech/geomesa
          path: ./geomesa
      - name: Set up Python 2.7
        uses: actions/setup-python@v2
        with:
          python-version: 2.7
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./geomesa/docs/requirements.txt
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('./geomesa/**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build docs with Maven
        run: mvn clean install -Pdocs -pl docs
        working-directory: ./geomesa
      - name: Copy docs
        run: |
          rm -r ./geomesa.github.io/documentation/current/*
          cp -r ./geomesa/docs/target/html/* ./geomesa.github.io/documentation/current/
      - name: Commit nightly docs
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email '7715322+elahrvivaz@users.noreply.github.com'
          git add --all ./documentation/current/
          if [[ -n $(git status --porcelain) ]]; then
            git commit -am "Nightly builds for $(date '+%Y-%m-%d %H:%M')" && git push
          fi
        working-directory: ./geomesa.github.io
