name: build-the-docs-test

on:
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          path: geomesa.github.io
      - name: Checkout GeoMesa source
        uses: actions/checkout@v4
        with:
          repository: locationtech/geomesa
          path: geomesa
          ref: emilio/fix_scoverage
      - name: Configure git user
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email '7715322+elahrvivaz@users.noreply.github.com'
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./geomesa/docs/requirements.txt
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Set latest.commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd geomesa
          git log -1 --format=%H > latest.commit
      - name: Build docs
        working-directory: ./geomesa
        run: mvn clean install -Pdocs -pl docs
      - name: Copy docs
        run: |
          rm -r ./geomesa.github.io/documentation/latest/*
          cp -r ./geomesa/docs/target/html/* ./geomesa.github.io/documentation/latest/
          mv ./geomesa/latest.commit ./geomesa.github.io/documentation/latest/commit
      - name: Set site URL
        working-directory: ./geomesa
        run: |
          sed -i "s|<url>https://www.geomesa.org/</url>|<url>https://www.geomesa.org/documentation/latest/site/</url>|" pom.xml
      - name: Build site
        working-directory: ./geomesa
        run: |
          mvn clean compile site -Dscala.maven.plugin.version=4.9.5
      - name: Stage site
        working-directory: ./geomesa
        run: |
          mvn site:stage -DstagingDirectory="$(pwd)/../geomesa.github.io/documentation/latest/site/"
      - name: Commit nightly docs
        working-directory: ./geomesa.github.io
        run: |
          git add --all ./documentation/latest/
          if [[ -n $(git status --porcelain) ]]; then
            git commit -am "Nightly builds for $(date '+%Y-%m-%d %H:%M')" && git push
          fi
