name: build-the-docs-test

on:
  workflow_dispatch:

env:
  MAVEN_CLI_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dtest.fork.count=1 --batch-mode

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          path: geomesa.github.io
      - name: Checkout GeoMesa source
        uses: actions/checkout@v4
        with:
          repository: locationtech/geomesa
          path: geomesa
          ref: emilio/fix_scoverage
      - name: Configure git user
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email '7715322+elahrvivaz@users.noreply.github.com'
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./geomesa/docs/requirements.txt
      # scoverage requires Java 17, even though we normally build with 11
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      # tracks the latest commit, to skip running nightly builds when nothing has changed
      - name: Set latest.commit
        working-directory: ./geomesa
        run: |
          git log -1 --format=%H > latest.commit
      - name: Build docs
        working-directory: ./geomesa
        run: mvn $MAVEN_CLI_OPTS clean install -Pdocs -pl docs
      - name: Copy docs
        run: |
          rm -r ./geomesa.github.io/documentation/latest/*
          cp -r ./geomesa/docs/target/html/* ./geomesa.github.io/documentation/latest/
          mv ./geomesa/latest.commit ./geomesa.github.io/documentation/latest/commit
      - name: Run scoverage
        working-directory: ./geomesa
        run: |
          mvn clean package $MAVEN_CLI_OPTS -Pscoverage
      - name: Build site
        working-directory: ./geomesa
        run: |
          # set the correct site url
          sed -i "s|<url>https://www.geomesa.org/</url>|<url>https://www.geomesa.org/documentation/latest/site/</url>|" pom.xml
          mvn generate-sources site $MAVEN_CLI_OPTS -Psite
      - name: Stage site
        working-directory: ./geomesa
        run: |
          mvn site:stage $MAVEN_CLI_OPTS -DstagingDirectory="$PWD/../geomesa.github.io/documentation/latest/site/"
      - name: Commit nightly docs
        working-directory: ./geomesa.github.io
        run: |
          git add --all ./documentation/latest/
          if [[ -n $(git status --porcelain) ]]; then
            git commit -am "Nightly builds for $(date '+%Y-%m-%d %H:%M')" && git push
          fi
